# Generated by Django 4.1.2 on 2023-10-20 13:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
